SELECT TOP 100 Cmp.[Name] as Distribuidor
      ,Cmp.[Contact] as NombreContacto
      ,[Ciudad]
      ,YEAR(FechaVenta) as AnioVenta
      ,Mes.Nombre as MesVenta
      ,[FechaVenta]
      ,[Zona]
      ,[ClienteTipo]
      ,[Categoria]
      ,[TipoRecursivo]
      ,[ClienteCodigo]
      ,[RazonSocial]
      ,[ClienteNombre]
      ,[NumeroNit]
      ,[NumeroFactura]
      ,[AutorizacionNumero]
      ,[CodigoControl]
      ,[TipoPago]
      ,[DocumentoEstado]
      ,[Vendedor]
      ,[Almacen]
      ,[Negocio]
      ,[Reclasificacion]
      ,[Segmento]
      ,[SubRubro]
      ,[ProductoCodigo]
      ,[ProductoNombre]
      ,[Bonificacion]
      ,[NumeroLote]
      ,[UnidadMedidaVenta]
      ,[FactorConversion]
      ,[ListaPrecio]
      ,[CantDISP_UN]
      ,[CantBU]
      ,[PrecioProducto]
      ,[TotalProducto]
      ,[DescuentoProducto]
      ,[Descuento2Producto]
      ,[DescuentoDocumento]
      ,[UsuarioTransaccion]
      ,[PesoNeto]
      ,[PesoBruto]
      ,[TotalKilosNetos]
      ,[TotalKilosBrutos]
      ,[CostoPrecioPromedio]
      ,[TotalCostoPromedio]
      ,[CMB_Monto]
      ,[CMB_Porcentaje]
      ,[NumeroGuia]
      ,[EstadoGuia]
      ,[RepartidorNombre]
      ,Year(FechaDespachoGuia) as AnioGuia
      ,Month(FechaDespachoGuia) as MesGuia
      ,[FechaCreacionGuia] 
      ,[FechaDespachoGuia] 
      ,[Descripcion]
  FROM [PIVOT].[VentasXFecha] VXF
       INNER JOIN [PIVOT].[extMsCompany] Cmp ON Cmp.Id = VXF.IdDistribuidor
	   INNER JOIN [PIVOT].[Meses] Mes ON Mes.Id = MONTH(VXF.FechaVenta)