USE [master]
GO

/****** Object:  Database [AVA_MSFSystem_Cube]    Script Date: 4/11/2019 4:56:01 PM ******/
CREATE DATABASE [AVA_MSFSystem_Cube]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AVA_MSFSystem_Cube', FILENAME = N'D:\DATABASES\SQL2016\SQLServer\AVA_MSFSystem_Cube.mdf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'AVA_MSFSystem_Cube_log', FILENAME = N'D:\DATABASES\SQL2016\SQLServer\AVA_MSFSystem_Cube.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AVA_MSFSystem_Cube].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET ARITHABORT OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET  MULTI_USER 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET QUERY_STORE = OFF
GO

USE [AVA_MSFSystem_Cube]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [AVA_MSFSystem_Cube] SET  READ_WRITE 
GO


